const lightTheme = {
    colors: {
      black: '#000',
      white: '#fff',
      //primary: '#00FD99',
      primary: '#FFF',
      // background: '#201B2C',
      // backgroundBar: '#110F19',
      // backgroundGradient: '',
      // blackOpacityBackgound: '#0a0a0a7d',
      // transparentBackground: '100%',
      // transparent: 'rgba(0, 0, 0, 0.0)',
      // textOnPrimary: '#000',
      // textOnSecondary: '#00FD99',
      // buttonOutlineColor: '#03E4B2',
      // //buttonGradientStart: '#00FD98',
      // buttonGradientStart: '#E75921',
      // buttonGradientEnd: '#E75921',
      // textOnBackground: '#EFEFFF',
      // lineColor: '#FFF',
      // inputPlaceholder: 'rgba(255, 255, 255, 0.4)',
      // checkboxBorder: '#FFF',
      // defaultBorder: '#4C4454',
      // defaultBottom: '#110F19',
      // backgroundInputLogin:'rgba(3, 1, 6, 0.5)',
      // backgroundInput:'rgba(3, 1, 6, 0.5)',
      // yellow: '#FFB800',
      // pink: '#FF40A7',
      // red: '#CE4444',
      // replyBackground: 'rgba(239, 239, 255, 0.2)',
      // shimmerPrimary: '#00FD9910',
      // shimmerSecondary: '#0a0a0a80',
      // chatMessageCard: '#151726',
      // chatMessageCardMe: '#474053',
      // chatMessageCardText: '#FFFFFF',
      // chatMessageCardTextDark: '#000000',
      // chatSender: '#151726',
      // chatSenderBorder: '#00FD99',
      // gradientCardStart: '#3F374C',
      // gradientCardEnd: 'rgba(0, 0, 0, 0.0)',
      // gradientCardBorderStart: '#00FD98',
      // gradientCardBorderEnd: '#0AAAEF',
      // textPendingColor: '#0AAAEF',
      // textCanceledColor: '#FF0000',
      // textDoneColor: '#00FD98',
      // textPendingTokenColor: '#E75921',
      // textContrastColor:'#E75921'
    },
    fontSizes: {
      mini: 6,
      smallest: 8,
      small: 10,
      regular: 12,
      big: 14,
      biggest: 16,
      huge: 20,
      plusHuge: 22,
      bigUltra: 24
    },
    fonts: {
      light: 'Poppins-Light',
      regular: 'Poppins-Regular',
      medium: 'Poppins-Medium',
      bold: 'Poppins-Bold',
      extraBold: 'Poppins-Black',
    },
  };
  
  export default lightTheme;
  